plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Jake
description: Just A Simple Blog Where I Share My Thoughts, Opinions and Experiences.
lang: en
locale: en_US
url: "https://jakesblog.netlify.app"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20